name: Build APK

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build type (debug or release)'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assemble${{ github.event.inputs.buildType }}

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk-${{ github.event.inputs.buildType }}
        path: app/build/outputs/apk/${{ github.event.inputs.buildType }}/*.apk
