name: Build Android app

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build type (debug or release)'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      outputType:
        description: 'Output type (.apk or .aab)'
        required: true
        default: '.apk'
        type: choice
        options:
          - '.apk'
          - '.aab'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build APK or AAB and Capture Logs
      run: |
        if [ "${{ github.event.inputs.outputType }}" == ".apk" ]; then
          ./gradlew assemble${{ github.event.inputs.buildType }} --info > build.log 2>&1
        else
          ./gradlew bundle${{ github.event.inputs.buildType }} --info > build.log 2>&1
        fi
    
    - name: Zip APK Logs
      run: |
        zip -r build-package.zip build.log

    - name: Upload Build Package
      uses: actions/upload-artifact@v2
      with:
        name: build-package-${{ github.event.inputs.buildType }}
        path: build-package.zip

    - name: Send Email with Build Package
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{ secrets.GMAIL_USER }} # 使用GitHub Secrets保护你的用户名
        password: ${{ secrets.GMAIL_PASS }} # 使用GitHub Secrets保护你的密码
        from: ${{ secrets.GMAIL_USER }} # 指定发件人邮箱地址
        to: wilson.lwt.tw@gmail.com
        subject: Build Artifacts and Logs
        body: Attached is the build package including the APK or AAB and build logs.
        attachments: build-package.zip
